name: CI/CD

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Docker Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0

  deploy:
    name: Deploy to DigitalOcean
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Droplet and Deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            git clone git@github.com:Salhi-Yassine/last-stack.git .
            
            SERVER_NAME=the-last-stack.duckdns.org \
            APP_SECRET=ChangeMe \
            CADDY_MERCURE_JWT_SECRET=ChangeThisMercureHubJWTSecretKey \
            docker-compose -f compose.yaml -f compose.prod.yaml up -d --wait